name: CF IPv4 Speedtest

on:
  schedule:
    - cron: "0 8 * * *"  # 每天 08:00 UTC (北京时间16:00)
  workflow_dispatch:      # 可手动触发

jobs:
  speedtest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Fetch CF IPv4 list
        run: |
          python get_cloudflare_ips.py

      - name: Run speedtest script
        run: |
          python speedtest_sample.py

      - name: Commit and push results
        if: success()  # 仅成功时提交
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add results/top20.txt
          git commit -m "Update top20.txt (auto speedtest)" || echo "No changes to commit"
          git push
